import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ChangeEvent } from "react";
import LayoutButtons from "@/components/layoutButtons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    {/* <div>(layout/preview.vueに相当するファイル)</div> */}
    <section className="w-[210mm] h-[297mm]">
      {children}
    </section>
    <LayoutButtons />
    </body>
</html>
)
  ;
}
