import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PreviewMenuHeader from "@/components/PreviewMenuHeader";
import { cn } from "@//utils/cn";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={cn(geistSans.variable, geistMono.variable, "antialiased")}
      >
        <section className="flex h-screen w-full flex-col print:h-full">
          <PreviewMenuHeader />
          <main className="flex-1 not-print:overflow-y-scroll">{children}</main>
        </section>
      </body>
    </html>
  );
}
